# Welcome to numpy

          
***Why We Use NumPy in Machine Learning (Easy Notes)***

- 🔹 NumPy = Numbers in Python (fast math library)  
- 🔹 Handles arrays & matrices (better than normal Python lists)  
- 🔹 Very fast for calculations (used inside ML libraries)  
- 🔹 Useful for linear algebra (dot product, transpose, etc.)  
- 🔹 Helps in data preprocessing (reshape, normalize data)  

✅ **NumPy = Fast calculations with arrays & matrices → backbone of ML**



In [1]:
import numpy as np

In [2]:
myarr = np.array([[2,4,7,9]], np.int16)

In [3]:
myarr

array([[2, 4, 7, 9]], dtype=int16)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int16')

# Array Creation: Conversion from other Python Structure

***Mostly we use built in functions***

In [6]:
myarray = np.array([[1,2,3],[4,5,6,],[7,8,9]])

In [7]:
myarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
myarray.shape

(3, 3)

In [9]:
myarray.dtype

dtype('int64')

In [10]:
myarray.size

9

In [11]:
zeroes = np.zeros((2,5))

In [12]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
zeroes.dtype

dtype('float64')

In [14]:
zeroes.size

10

In [15]:
rng = np.arange(15)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
lspace = np.linspace(1,6,10)

In [18]:
lspace

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [19]:
emp = np.empty((1,6))

In [20]:
emp

array([[2.14321575e-312, 2.35541533e-312, 2.44029516e-312,
        2.12199579e-312, 2.56761491e-312, 2.14321575e-312]])

In [21]:
emp_like = np.empty_like(lspace)

In [22]:
emp_like

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [23]:
ide = np.identity(45)

In [24]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [25]:
arr = np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr = arr.reshape(3,33)

In [28]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

***Attributes and Methods***

In [30]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [33]:
ar = np.array(x)

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
ar.sum(axis=0)

array([12, 15, 18])

In [37]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [38]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
ar.flat

In [40]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [41]:
ar.ndim

2

In [42]:
ar.size

9

In [43]:
ar.nbytes

72

In [44]:
one = np.array([1,2,344,5])

In [47]:
one.argmax()


np.int64(2)

In [48]:
one.argmin()


np.int64(0)

In [49]:
one.argsort()


array([0, 1, 3, 2])

In [51]:
ar.argsort(axis=1)


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [52]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

***Mathematical matrics operations***

In [54]:
ar2 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
ar+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [56]:
ar *ar2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [57]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [60]:
np.where(ar>6)

(array([2, 2, 2]), array([0, 1, 2]))

In [61]:
np.count_nonzero(ar)

np.int64(9)

***Check size and see diff btw py or numpy***

In [64]:
import sys

In [62]:
py_arr = [1,3,5,7,8]

In [63]:
np_arr = np.array(py_arr)

In [66]:
sys.getsizeof(1) * len(py_arr)

140

In [67]:
np_arr.itemsize * np_arr.size

40